module.exports={
    PRODUCT_HELPERS:'Product',
    USER_HELPERS:'User',
    CATEGORY_HELPERS:'Category',
    CART_HELPERS:'Cart',
    ORDER_COLLECTION:'Order',
    BANNER_COLLECTION:'Banners',
    WISHLIST_COLLECTION:'Wishlist',
    ADDRESS_COLLECTION:'Address',
    COUPON_COLLECTION:'Coupon',
    WALLET_COLLECTION:'wallet'
}